### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bayurex** [tahaluindo/Gmail-Bot#1]
Sorry karena saya bukan user python, ini error gara2 apa ya?

```
  __________  ____   __________  __
 / ___/ __/ |/ / /  /  _/ __/\ \/ /
/ (_ / _//    / /___/ // _/   \  /
\___/___/_/|_/____/___/_/     /_/

[#] Mass Creator Akun GMAIL With OTP

[#] Made by Genlify Translate by Tahaluindo

[#] SETTINGS:
[>] Threads: 1
[>] Use Proxy: True
[>] Proxy Protocol: HTTP
[>] Working Proxy Amount: 27

[>] Press "Enter" to continue.
[{'thread': {'id': 1, 'status': 'Initiating', 'Total_Creating': 0, 'error': 0}}]
Exception in thread Thread-401 (thread_function):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2032.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\belajar\Gmail-Bot\src\igniter.py", line 42, in thread_function
    data = worker(full_name, f"{full_name[0]}{full_name[1]}{random.randint(1,999)}", get_random_string(12), random.choice(ua), self.config["api_key"], self.CLI, thread_id, random.choice(self.proxies) if self.proxies else None).create_account()
  File "D:\belajar\Gmail-Bot\src\worker\generator.py", line 56, in __init__
    self.driver = webdriver.Chrome(options=self.options, desired_capabilities=capabilities)
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chrome\webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\chromium\webdriver.py", line 92, in __init__       
    super().__init__(
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 270, in __init__        
    self.start_session(capabilities, browser_profile)
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in start_session   
    response = self.execute(Command.NEW_SESSION, parameters)
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PC SPASIAL 29\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
Backtrace:
        Ordinal0 [0x00DED953+2414931]
        Ordinal0 [0x00D7F5E1+1963489]
        Ordinal0 [0x00C6C6B8+837304]
        Ordinal0 [0x00C87A8E+948878]
        Ordinal0 [0x00C85FB1+942001]
        Ordinal0 [0x00CB9100+1151232]
        Ordinal0 [0x00CB8D5A+1150298]
        Ordinal0 [0x00CB42B6+1131190]
        Ordinal0 [0x00C8E860+976992]
        Ordinal0 [0x00C8F756+980822]
        GetHandleVerifier [0x0105CC62+2510274]
        GetHandleVerifier [0x0104F760+2455744]
        GetHandleVerifier [0x00E7EABA+551962]
        GetHandleVerifier [0x00E7D916+547446]
        Ordinal0 [0x00D85F3B+1990459]
        Ordinal0 [0x00D8A898+2009240]
        Ordinal0 [0x00D8A985+2009477]
        Ordinal0 [0x00D93AD1+2046673]
        BaseThreadInitThunk [0x76B66739+25]
        RtlGetFullPathName_UEx [0x77498FD2+1218]
        RtlGetFullPathName_UEx [0x77498F9D+1165]
```

**Comment by zailbreck** [comment]
Itu kan ada errornya 
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary

Pastiin udah install chrome dan sesuaikan versi chromedriver nya sama versi chrome yang di install

**Comment by rhymsc** [comment]
**ini gimana bang**

sh: 1: title: not found
[Boot][16:59:11] Reading config.
[Error][16:59:11] Check your config file for values.

**Comment by ilyassayunus** [comment]
> **ini gimana bang**
> 
> sh: 1: title: not found [Boot][16:59:11] Reading config. [Error][16:59:11] Check your config file for values.

sama
